Initial version of the plugin
OneIdentity/safeguard-sessions-plugin-servicenow pull request #1
Opened 2020-05-28 15:48 UTC by gorosz

Signed-off-by: Gergely Orosz <gergely.orosz@oneidentity.com>

2020-05-28 16:44 UTC, gasparb16 commented on lib/plugin.py
> +        return AAResponse.deny(
#optional: For me it would be clearer if this return happens in an else statement

2020-05-28 16:45 UTC, gasparb16 approved these changes

2020-05-29 07:12 UTC, krajorama requested changes
minor issues

2020-05-29 07:12 UTC, krajorama commented on Pipfile
> +oneidentity-safeguard-sessions-plugin-sdk = "*"
IIRC we check the SDK version at plugin release, so this should be `= "~=1.3.0"` to match the MANIFEST

2020-05-29 07:12 UTC, krajorama commented on lib/plugin.py
> +        return
redundant, if you want to show this branch I'd suggest writing: `else: return None`

2020-05-29 07:12 UTC, krajorama commented on lib/tests/conftest.py
> +        gwuser=46c6f9efa9fe198101ddf5eed9adf6e7
should go to site specific info like username/password

2020-05-29 07:12 UTC, krajorama commented on lib/tests/test_plugin.py
> +            key_value_pairs={"otp": "", "tkt": ticket_id},
tkt should be enough

2020-05-29 07:12 UTC, krajorama commented on lib/tests/test_plugin.py
> +
missing empty line

2020-05-29 07:12 UTC, krajorama commented on main.py
> +#   Copyright (c) 2018-2019 One Identity
2020

2020-05-29 07:12 UTC, krajorama commented on lib/wrap.py
> +import re
missing copyright

2020-05-29 07:12 UTC, krajorama commented on lib/wrap.py
> +blacklist = ["(?i).*_password"]
move into Filter class as BLACKLIST

2020-05-29 07:12 UTC, krajorama commented on lib/wrap.py
> +import datetime
datetime is not used

2020-05-29 07:12 UTC, krajorama commented on lib/tests/test_plugin.py
> +    authorize_params["cookie"] = deepcopy(authentication_result["cookie"])
optional: there's a function to handle verdict cookies since 1.2.0: `from safeguard.sessions.plugin_impl.test_utils.plugin import update_cookies`

2020-05-29 07:12 UTC, krajorama commented on lib/tests/test_plugin.py
> +from requests.exceptions import HTTPError
unused import

2020-05-29 07:12 UTC, krajorama commented on MANIFEST
> +api: 1.2
RequestsTLS was only introduced in 1.3.0

2020-05-29 07:12 UTC, krajorama commented on lib/tests/conftest.py
> +            gwuser=46c6f9efa9fe198101ddf5eed9adf6e7
same as above

2020-05-29 07:12 UTC, krajorama commented on lib/plugin.py
> +            return AAResponse.accept(reason="Verified ServiceNow request: {}".format(ticket_id))
`ticket_id={}`

2020-05-29 07:12 UTC, krajorama commented on lib/plugin.py
> +            reason="Ticket verification failed. No ServiceNow request matched by the provided query".format(ticket_id))
`ticket_id={}`

2020-05-29 07:12 UTC, krajorama commented on lib/plugin.py
> +        self.logger.info("Updating Service Now ticket with id: {}".format(ticket_id))
ticket_id={}

2020-05-29 07:12 UTC, krajorama commented on lib/plugin.py
> +            self.logger.debug("Unable to update Service Now ticket with id: {}".format(ticket_id))
ticket_id={}

2020-06-05 11:43 UTC, krajorama approved these changes
LGTM - do add a readme like the other plugins before the first version is released.

2020-06-08 08:41 UTC, merged